### ISSUE TITLE
Accept files that are uploaded by the user as a background

### ISSUE THREAD

**Issue by choyiny** [choyiny/pdf-editor#3]
Right now, you can only specify a link to change the background picture. Add an upload button where users can select the background picture from their own file system with javascript.

**Comment by deepansh946** [comment]
I would like to work on this.

**Comment by choyiny** [comment]
Sure!

**Comment by Aravind22** [comment]
Is this resolved yet? if not, I can work on it.

**Comment by choyiny** [comment]
Yes @Aravind22, feel free to work on it.

**Comment by choyiny** [comment]
fixed in #4
